### ISSUE TITLE
[gd-extension] Linux Release Build requiring specific libstdc++

### ISSUE THREAD

**Issue by cridenour** [2shady4u/godot-sqlite#128]
**Environment:**
 - OS: Linux
 - Godot version: 4.0-beta12
 - _godot-sqlite_ version: 4.0-beta12

**Issue description:**
ERROR: Can't open dynamic library: addons/godot-sqlite/bin/libgdsqlite.linux.template_release.x86_64.so. Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /media/LinuxStorage/Games/Steam/steamapps/common/Drift Playtest/libgdsqlite.linux.template_release.x86_64.so)

**Steps to reproduce:**
Run on a machine not used to build the project (reported by a playtester)

**Minimal reproduction project:**
N/A

**Additional context**
I'm not sure if this is a godot-sqlite or a godot-cpp issue. Windows has a dynamic requirement that could be solved by compiling with mingw. Not sure what the Linux equivalent would be.

**Comment by 2shady4u** [comment]
Hi @cridenour 

This is because the library is compiled with a certain GLIBCXX version that is set by the version of Ubuntu used to build the library.
See the note here:
https://github.com/2shady4u/godot-sqlite#5-is-this-plugin-compatible-with-a-godot-server-binary-how-to-set-it-up

If I remember correctly:
Ubuntu 20.04 LTS = glibcxx 3.4.29
Ubuntu 18.04 LTS = glibcxx 2.28
Ubuntu 16.04 LTS = glibcxx 2.23 (NOT supported by Github Actions anymore 😢 )

So it might be best to swap out the `libgdsqlite.linux.template_release.x86_64.so`-binary with the one compiled by Ubuntu 18.04 to reach the largest possible Linux demographic. (The artifact with the name `x11-legacy`)

The user can find out his/her glibcxx version by using following command:
```
ldd --version
```

**Comment by cridenour** [comment]
Makes sense! Confirmed with the user they are indeed running 18.04 / 2.28. 

Thanks for the explanation and should be an easy fix!
