### ISSUE TITLE
Add export support to triggers

### ISSUE THREAD

**Issue by Thebas** [2shady4u/godot-sqlite#34]
Hey 2Shady4me, it's me again... :D
If we add triggers to be created in the DB (importing from JSON (amazing feature BTW)), those trigger are not exported if we then do the "export_to_json" thingy.

Add something like this to a previously exported json:
   ```
 {
        "name": "exercises_ad",
        "sql": "CREATE TRIGGER exercises_ad AFTER DELETE ON exercises BEGIN INSERT INTO virtual_exercises (virtual_exercises, rowid) VALUES ('delete', old.id); END;",
        "row_array": [
        ]
    }
```
Import it(I confirm it is added to the DB), then export.
Look at the file.
SPOILER: It's gone!

It's not a massive deal, I just wanted to let you know!
Thank you!

P.S.: That trigger looks strange but it works for virtual tables.
P.S.2: CREATE TRIGGER exercises_ad AFTER DELETE ON exercises BEGIN DELETE FROM virtual_exercises WHERE rowid = old.id; END

**Comment by 2shady4u** [comment]
Hi @Thebas 
I've been meaning to rework the import from/export to JSON functionalities.
One of the bigger issues I'm having is how to store BLOBs in JSON.
The brute force method would be to just dump the binary data into JSON, but there might be better ways.

Things like foreign keys are also not supported in JSON, so that might also be implemented in some way in the future...

**Comment by Willowblade** [comment]
Base64 encoding of binary data in JSON is pretty fast and easy imo

**Comment by 2shady4u** [comment]
BLOBS now get encoded/decoded to base64 when exporting/importing from JSON

**Comment by 2shady4u** [comment]
@Thebas saving/loading triggers to/from JSON has now been implemented in latest commit on the dev branch and will be part of the next release.
