### ISSUE TITLE
Help: Accessing the database on an Android device

### ISSUE THREAD

**Issue by lucassene** [2shady4u/godot-sqlite#46]
Hey wonderful work here, but I'm in trouble trying to access the database on an Android device, I did the copy to user thing, but I'm always getting the "failed to access path" print. Any suggestion?

My code:

```
const SQLite = preload("res://addons/godot-sqlite/bin/gdsqlite.gdns")

var database

func load_database():
	database = SQLite.new()
	database.path = _get_db_path()

func query(string):
	database.open_db()
	database.query(string)
	var result = database.query_result
	database.close_db()
	return result

func insert(table,data):
	database.open_db()
	database.insert_row(table,data)
	database.close_db()

## Later I'll add logic to prevent copying the database to user more than once
func _get_db_path():
	var dir = "res://data/database/game_database"
	if OS.get_name() == "Android" or OS.get_name() == "iOS":
		dir = "user://data/database/game_database"
		_copy_data_to_user()
	return dir

## I copied and pasted the code from your demo
func _copy_data_to_user():
	var data_path = "res://data/database"
	var copy_path = "user://data/database"

	var dir = Directory.new()
	dir.make_dir(copy_path)
	if dir.open(data_path) == OK:
		dir.list_dir_begin();
		var file_name = dir.get_next()
		while (file_name != ""):
			if dir.current_is_dir():
				pass
			else:
				dir.copy(data_path + "/" + file_name, copy_path + "/" + file_name)
			file_name = dir.get_next()
	else:
		print("failed to access path")

func _exit_tree():
	database.close_db()
```
Kind regards,
Lucas Sene

**Comment by 2shady4u** [comment]
Hello @lucassene 

Some potential issues I see:
- Since you are attempting to create multiple directories (`data` & `database`), you'll have to use the `make_dir_recursive()`-function instead of the `make_dir()`-function as described [here](https://docs.godotengine.org/en/stable/classes/class_directory.html#class-directory-method-make-dir-recursive). I would also propose adding a temporary print to that statement so you can see if the directories actually get created successfully (i.e. `print(make_dir_recursive())`).
- Are you sure the directory `res://data/database/game_database` (and its contents) actually gets copied? Did you correctly add this path to your export settings? (see the demo project's [export_preset.cfg](https://github.com/2shady4u/godot-sqlite/blob/master/demo/export_presets.cfg))

Some other useful hints:
- Best to make sure your result array is duplicated when you return it (i.e. `return result.duplicate()`) to stop future queries from **deleting** (= `.clear()`) your result. (Since Arrays are passed by reference, as documented [here](https://docs.godotengine.org/en/stable/classes/class_array.html).
- Calling `open_db()` and `close_db()` every time you do a query might be overkill and slow down your program if you are doing thousands of queries. In most cases opening the database once (in the `_ready()` function for example) is sufficient.

**Comment by lucassene** [comment]
Thanks a lot @2shady4u ! The project is not only running on Android now, but you also solved another question of mine regarding the best practice on opening and closing the database.

The fault regarding the original issue was in 2 places:

1. The `make_dir_recursive()` thing you've said;
2. The fact that I did not include the *.db in the Export > Resources. Probably the Godot was not exporting the database file.

Kind regards,
Lucas Sene
