### ISSUE TITLE
GD-SQLite no longer working in Linux versions 

### ISSUE THREAD

**Issue by vainn2000** [2shady4u/godot-sqlite#52]
**Environment:**
 - OS:  Ubuntu 18 and 20 and Deb
 - Godot version: 
 - _godot-sqlite_ version: 

**Issue description:**
Every time script tries to create an new DB instance it causes a segmentation fault.
Works fine in windows

**Steps to reproduce:**
Verified on 3 different Linux versions.

**Minimal reproduction project:**
```
extends Node

#Setup for the AWS server
# Comment out local and remove comment for the d.path ubuntu to use for the AWS server
# Be sure to leave the SQLite alone.

var network = NetworkedMultiplayerENet.new()
var port = 1911 #Port for Gateways clients to connect to
var max_servers = 5

# Preload the database SQLite software module
var SQLite = preload("res://addons/godot-sqlite/bin/gdsqlite.gdns")


# Players dict stored as id:name
var players = {} #This should be transfered to the second singleton that deals with the actuall games and players connections
var check_player = {}
var db
#var db_name : String = "res//db/alpha2_test_jog_db"  # Remove comment if logins dont work, seem to work
#var db_name : String = "/home/ubuntu/jogalpha3/db/alpha2_test_jog_db"
var table_name : String = "users"


func _ready():
	StartAuthenticationServer() # GatewayServer connects to this


# Loading the Creating the database for the users
	db = SQLite.new()
	db.path = "res://db/alpha2_test_jog_db" # Use this for LOCAL TESTING with editor
```

**Additional context**
Not sure if it's the newer 2.4 SQLite wrapper that is the issue. Older versions no longer found on the Asset Lib.

**Comment by 2shady4u** [comment]
Hi @vainn2000,

Could you try the following:
- Download the latest version LEGACY version of godot-sqlite as found here as see if that fixes it:
https://github.com/2shady4u/godot-sqlite/actions/runs/819913518
- Find out the version of your glibc on your Linux OS using following command:
`ldd --version`
- I see you are using an AWS server? What is the glibc version of this server?

As found in the docs:
***NOTE**: If you are using an older version of Linux on your server machine (with glibc version < 2.28), the plugin crashes due to the compiled version of glibc being too recent. In that case you can either recompile the Linux plugin binary yourself or you can download the legacy binaries (Ubuntu 16.04 with glibc version == 2.23) as found [here](https://github.com/2shady4u/godot-sqlite/actions/workflows/linux_builds.yml).*

Greetings!

**Comment by vainn2000** [comment]
Thank you Piet
Will try this all out and let you know. My knowledge of DB's are pretty
much non existent. I basically hack at stuff and eventually get things to
work with a lot of help from the internet and awesome guys like you.
Curious, how much knowledge do you have of Godot and databases?
Do you have a DB recommendation for something a little more powerful that
works well with Godot? Looking more for something that is good for
containing data on player/users matchwin s losses etc.

Sincerely Lee Ramer
Le

**Comment by vainn2000** [comment]
Ubuntu 20.04 Lts
glibc version - 2.31-0 ubuntu9.2

hmmm looks like it is an updated version for it's greater than 2.28 like
you stated.

**Comment by 2shady4u** [comment]
Hi @vainn2000 ,

Most of this depends on what you are actually trying to achieve.
SQLite is a good database engine when you want something light-weight that doesn't need to do any heave lifting like storing millions of rows, updating them at once, etc...)
As a direct result it is a very good database engine for beginners since it is quite easy to learn (In comparison to databases that run their own server, like MySQL)

There's other plugins available that aim to create connectors to database servers:
https://github.com/Marzin-bot/PostgreSQLClient
https://github.com/Malkverbena/MySQL_Module

(and many more, but I never tested any of them)

**Comment by vainn2000** [comment]
I was looking at post greSQL client for the future when I plan on having a
lot more players and a little more data related to money transactions as
well.
You are right, I chose SQL lite for it's simplicity and ease on
learning about Databases.
Is this your field of study? Computer science etc?

**Comment by vainn2000** [comment]
Hi Piet
When I click on the link I get two options of ubuntu 18 and 16 with this
but no versions of godot-SQLite
Lock emsdk version to 2.0.17
🐧 Linux Builds #60

**Comment by 2shady4u** [comment]
Here's a direct link to the legacy version:
https://github.com/2shady4u/godot-sqlite/suites/2675239108/artifacts/58959492

Here's a direct link to the NON-legacy version:
https://github.com/2shady4u/godot-sqlite/suites/2675239108/artifacts/58959491

**Comment by vainn2000** [comment]
Hmmmm. I re-exported using Godot Server vers 3.2.3 with putting the Legacy
libgdsqlite.so directly into the X11folder then exported.
Same thing.
Tried current lib.so file as well as same thing.
No one has contacted you with this issue? Wondering if it's just me.

**Comment by 2shady4u** [comment]
Hello @vainn2000 

I've just tested the demo-project of Godot-SQLite on Ubuntu 20.04 LTS.
Everything seems to work just fine on my device 🤔 

![Capture](https://user-images.githubusercontent.com/42484461/124397974-8a56e600-dd13-11eb-9d51-9c095edf1ff8.PNG)

Some questions/things to try out:
1. Since you are running the Server.exe on a AWS Server, could you check what the glibc version is on this AWS server?
In almost all cases, the problem that you are facing (seg fault) is caused by a glibc version that is too old.
Or are you running the server on your own device? (the Ubuntu LTS 20.04?)

2. Similarly, does this seg fault only appear after exporting? Does this seg fault appear when you run the game in the editor?

3. Could you run the demo-project and see if that works?
Alternatively this seg fault could also be caused by Godot itself, so be sure to check if you get the same problem when you 
do not instance/load the GDNative class. Also, could you run the demo-project and see if that works?

As a last resort, could you send me if possible a minimum reproduction project? (Just drag & drop a zip archive here)

**Comment by vainn2000** [comment]
Thanks 2Shady4u
Nice to know that is working on Ubuntu 20. Vers
I have some time this week and will try what you suggested.
Works fine with windows when I retested my code just to see.
Will let you know later this week
Thanks for all your help.
Really appreciated


Lee Ramer

**Comment by jorderator** [comment]
Hi, I'm having the same issue. I can run the project fine in the editor, everything works as expected. Once I export the project to an executable it runs with some errors and then segfaults when the database is opened. I have not tested on other platforms yet, and I can provide a minimal demo project if need be. You mentioned checking if it happens when not instancing the GDNative class. I don't know what that is yet, but I might look into that and see if that works.

Details are as follows:
OS: Arch Linux, version 5.12.10-arch1-1
Godot: v3.3.2.stable
Godot-SQLite: 2.4
glibc: 2.33

Output when running exported project (with comments):
```
$ ls
libgdsqlite.so  player_data.db  server-proto.64  server-proto.pck
$ ./server-proto.64
Godot Engine v3.3.2.stable.official - https://godotengine.org
 
ERROR: init_library: Condition "lib_path.length() == 0" is true.   |
   At: modules/gdnative/nativescript/nativescript.cpp:1459.        |  Unknown error messages since adding GDSQLite, 
ERROR: get_as_text: Condition "!f" is true. Returned: String()     |   don't appear to break anything, but may be
   At: core/bind/core_bind.cpp:2126.                               |   connected to the problem.
ERROR: parse: Error parsing JSON at line 0:                        |  
   At: core/bind/core_bind.cpp:3292.                               |
Server started
User 886162351 Connected
Authenticating for player 886162351     |  After this message, the server checks user credentials against db
Segmentation fault (core dumped)
```

**Comment by 2shady4u** [comment]
@jorderator I'll have some time in the weekend hopefully to look into this.

Does this problem also exist when:
- You export the demo-project?
- You export in debug mode? You export in Release mode?

I'll export the demo-project as well on Ubuntu 20.04 LTS and I'll see what happens on my end.

**Comment by jorderator** [comment]
I found the problem. It's the godot server binary. I just tried both regular export and by-hand export for both server and regular godot binary, and with or without debug it's the server binary that causes it. This happens across the demo project and mine.

Here is output for the demo project running through the server binary:
```
$ ./demo.x64
Godot Engine v3.3.2.stable.official - https://godotengine.org
 
CORE API HASH: 0
EDITOR API HASH: 0
Loading resource: res://default_env.tres
Loading resource: res://Main.tscn
Loading resource: res://database.gdc
Loading resource: res://addons/godot-sqlite/bin/gdsqlite.gdns
Loading resource: res://addons/godot-sqlite/bin/gdsqlite.gdnlib
ERROR: init_library: Condition "lib_path.length() == 0" is true.
   At: modules/gdnative/nativescript/nativescript.cpp:1459.
Loading resource: res://icon.png
Loading resource: res://Main.gdc
Segmentation fault (core dumped)
```

Regular godot binary gives the output you would expect.

**Comment by 2shady4u** [comment]
is the server entry present in the gdnlib file?

**Comment by jorderator** [comment]
Nope, it wasn't, that's it. After some research I added the server line back in, as per #50, recompiled (just using "Export Project" with Linux preset, using the server binary as the custom preset) and it worked fine. 

Thanks! Hopefully that means it's an easy fix!

**Comment by 2shady4u** [comment]
@vainn2000 could you check if adding the missing Server entry in the gdnlib file (as seen in #50 ) fixes the problem for you?

**Comment by vainn2000** [comment]
Will do, glad to see I wasn't the only one having the issue.

**Comment by vainn2000** [comment]
Okay sorry for the late reply, I just did a test run with my authentication
server and it appears to work now when I run it and have the DB opening.
Before I would get the error.
Great job since I know jack crap about linux and DB's beyond the basics for
getting my game up and running.
Much appreciated!!!

**Comment by 2shady4u** [comment]
@vainn2000 and @jorderator 
Thank you both for reporting and solving this bug together with me!
The Assetlib version has been updated to version 2.5 and hopefully this issue won't appear again 😱 
If it does... please do open this issue again! (or brand-new one ofc!)

**Comment by vainn2000** [comment]
You are welcome Piet.
Thanks for making the SQLite addon.
Very much appreciated.

Lee Ramer

**Comment by jorderator** [comment]
No worries at all! I'm glad to have helped. I just tried exporting with the updated assetlib version and it seems to run fine.

Like @vainn2000 said, thanks for developing this project and helping us out.
