### ISSUE TITLE
Can't open dynamic library:

### ISSUE THREAD

**Issue by holywar20** [2shady4u/godot-sqlite#57]
I am not positive this is a bug - but it's definitely unexpected. 

**Environment:**
 - OS: Windows 10
 - Godot version: 3.3.3
 - _godot-sqlite_ version: 2.2
 
 I had set this up on 2 computers months ago. Got a new machine, pulled my code from github ( which already had the addon installed and configured ) , and I got this error.
 
 Removing the addon, and reinstalling the addon did not correct it. The path indicated in the error message is the correct path. Same issue if I run Godot as an administrator.
 
 Console Log:
 
```
ERROR: Can't open dynamic library: C:/code/TitansReach3/addons/godot-sqlite/bin/win64/libgdsqlite.dll, error: Error 126: The specified module could not be found.
.
   At: platform/windows/os_windows.cpp:2425
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:502
ERROR: init_library: No nativescript_init in "res://addons/godot-sqlite/bin/win64/libgdsqlite.dll" found
   At: modules/gdnative/nativescript/nativescript.cpp:1482
```

```
const SQLite = preload("res://addons/godot-sqlite/bin/gdsqlite.gdns")

func _init():
	db = SQLite.new() // Errors on this line
	db.path = CORE_DB_PATH
	db.verbose_mode = false
	db.open_db()
```

GDScript Error
``` Attempt to call function 'new' in base 'NativeScript' on a null instance ```

It looks like it just can't find a library file. It's clearly an environment issue, since this exact code works two another systems. But I'm sort of at a loss of where to even start troubleshooting this.

Baring a sense of what the exact issue is, any insight into what I can do to fix this?

**Comment by 2shady4u** [comment]
Most likely this is due to not having the proper VC++ redistributables installed on the new device as discussed here https://github.com/2shady4u/godot-sqlite/issues/33

Basically due to way that godot-cpp is set up, the plugin expects certain redistributables to be installed on your device and crashes if it doesn't find them...

## Possible solutions:
1. Install the missing redistributables on your new device as found [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) (`vc_redist.x64.exe`).   
**Advantage:**  
_Smaller build size_
**Disadvantage:**
_Your windows build won't work on user devices unless the proper redistributables are installed._

2. Switch to a build compiled with MinGW as found [here](https://github.com/2shady4u/godot-sqlite/actions/runs/1123757632) (`win64-cross`) and replace the `libgdsqlite.dll` library with this new one.
**Advantage:**
_Your windows build should work on all devices_
**Disadvantage:**
_Big build size_

If your goal is to support Windows, it might be easiest to switch to a cross-compiled (MinGW) build instead.
If your goal is to support other platforms that are not Windows (such as Android) and you are just using Windows as a development platform, then just download the redistributables.

These steps should hopefully fix it.

**Comment by holywar20** [comment]
You were correct it was just a missing dependency on my end. I'm not a C++ developer, so that did not even occur to me.

That's a bit of a wrinkle I wasn't expecting actually. It's likely I'll need to do the second option whenever I try to release the game. It's an RPG, but I find Databases a really effective way to deal with data, rather than .json. Easier to Parse and filter, and it makes dealing with and loading saved games trivially easy.  Had I known I'd need to mess with redistributables and compiling in external libraries I might have chosen another approach.

But It works and that is a problem for another day.

Also thank you in general for this project. It's been very helpful and allowed me to leverage my skills in web to moonlight in game-development, which has saved me valuable time. So Kudos for that. This is the first problem I ran into. Everything is awesome and easy to use otherwise.

**Comment by 2shady4u** [comment]
Second option should work perfectly in your case then. Size increase shouldnt be that big of an issue. 

Thank you for using my project :blush:
