### ISSUE TITLE
Any plans to port this from gdnative to gdextension?

### ISSUE THREAD

**Issue by 01271** [2shady4u/godot-sqlite#59]
GDExtension is set to replace gdnative and I was wondering if there were any plans to port it over.
https://godotengine.org/article/introducing-gd-extensions

**Comment by 2shady4u** [comment]
Hello @01271
I'm definitely planning to port the plugin to gdextensions. 
However, I can't promise any ETA as I'm currently too busy working on other projects.

**Comment by kb173** [comment]
Hi! I noticed you already have a branch for the port. What's the state of it, is there any way to help?

For reference, I recently got our Geodot plugin working as a GDExtension: https://github.com/boku-ilen/geodot-plugin/compare/gdextension it's functional (the demos run in 4.0), but still workaround-y at parts.

**Comment by 2shady4u** [comment]
Hey @kb173,
Everything is more or less working as intended! 😄 
Currently, I am waiting for the implementation of the missing `ptr()` and `ptrw()`-methods in **PackedByteArray**s which
are required to read and write BLOB data from the SQLite database.

Due to this I also didn't start with porting the Godot <-> SQLite VFS as it is quite dependent on these methods.  

Other than that everything seems to be working order! (at least on Windows)

**Comment by kb173** [comment]
Very nice! I just tested it on Linux and it compiles and works too - I just had to add `linux.64.debug = "bin/libgdsqlite.linux.debug.64.so"` to the `gdsqlite.gdextension` definition.

Thanks for your work!

**Comment by 2shady4u** [comment]
Please move any possible discussion about the upcoming port to GDExtension to #71
