### ISSUE TITLE
Reduce binary size

### ISSUE THREAD

**Issue by boruok** [2shady4u/godot-sqlite#72]
**Is your feature request related to a problem? Please describe.**

Is here any way to reduce binary size? for example, stripped sqlite binary size is **1.6mb** compared to plugins x11 **4.6mb**. 
**Describe the solution you'd like**

It might be useful on platforms where app size is important.

**Describe alternatives you've considered**

(https://www.sqlite.org/footprint.html)
**Additional context**

N/A

**Comment by 2shady4u** [comment]
Hi @boruok,
The larger binary size is due to the GDNative interface being part of the binary vs. compiling a binary without any wrapper.

I don't really now if it is possible to reduce the binary size on my end? There might be some compiler flags that succeed in pushing down the size, but I'm not a compiler flag expert.

Out of curiosity, do you have a target application or a personal project that requires this reduction?

**Comment by boruok** [comment]
@2shady4u this personal (commercial) project for mobile devices.
So, i've managed to quicktest linux build, decreased libgdsqlite.so size from **4.6mb** to **3.7mb**.
1. change CCFLAGS from -O3 to -Os
2. strip generated binary

I wonder if there is an option to disable unwanted bindings on godot-cpp side...

**Comment by 2shady4u** [comment]
Closing this one due to inactivity 😄 
Also as the addition/removal of compiler flags is fully managed by the `godot-cpp`-repository, any changes to those flags should be addressed [there](https://github.com/godotengine/godot-cpp).
